name: elevation_map
description: "Строит график высот по двум точкам на карте."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  
  flutter_map: ^8.1.1
  flutter_map_math: ^0.2.1
  latlong2: ^0.9.1
  flutter_map_cache: ^2.0.0+1
  path_provider: ^2.1.5
  
  http_cache_hive_store: ^5.0.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  provider: ^6.0.5
  http: ^1.3.0
  fl_chart: ^0.71.0
  flutter_launcher_icons: ^0.14.3
  lru_cache: ^0.0.2
  vector_map_tiles: ^9.0.0-beta.8
  flutter_dotenv: ^5.2.1
  mapbox_maps_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  injectable_generator: 
  build_runner:

flutter:

  uses-material-design: true
  assets:
    - .env


flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/map-100.png"
  image_path_ios: "assets/map-100.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/map-100.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/map-100.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/map-100.png" # only available for Android 13 devices and above
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

